<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WssArtifactDir Condition="'$(WSS_ARTIFACT_DIR)' == ''">$(MSBuildProjectDirectory)\..\SubModules\HFI_WSS_Csharp_Implementation\lib</WssArtifactDir>
    <WssArtifactDir Condition="'$(WSS_ARTIFACT_DIR)' != ''">$(WSS_ARTIFACT_DIR)</WssArtifactDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubModules\HFI_WSS_Csharp_Implementation\src\Wss.CSharpImplementation.csproj" />
    <Reference Include="WSS_Core_Interface">
      <HintPath>$(WssArtifactDir)\WSS_Core_Interface.dll</HintPath>
    </Reference>
    <Reference Include="WSS.Transport.Serial">
      <HintPath>$(WssArtifactDir)\WSS.Transport.Serial.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
